### ISSUE TITLE
Uncaught ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by ilyar** [ever-guild/blockchain-explorer#3]
```bash
yarn
yarn start
```
open http://localhost:3000/
```log
Uncaught ReferenceError: Buffer is not defined
    at index.1119c913.js:15:241786
    at index.1119c913.js:1:142
    at index.1119c913.js:515:33768
```

**Comment by ilyar** [comment]
@TrueCarry please help

**Comment by TrueCarry** [comment]
```
        <script>window.global = window;</script>
        <script type="module">
            import { Buffer } from "buffer";
            
            window.Buffer = Buffer;
        </script>
        <script type="module" src="./src/app.ts"></script>
```
In index.html

**Comment by ilyar** [comment]
@TrueCarry thx
